# CORRECTED stellar.toml
NETWORK_PASSPHRASE = "Public Global Stellar Network ; September 2015"

      ACCOUNTS=[
      "GBG35LS6GFWPZRC2T7O2FGXO2KQRQYLF5237YDWXXRFZRQHDKRP6EM3J",
      "GBOYFPATHXCTWMDPC2U2KLGMUCJPCWTOYTLJN5U4B76XO7OWKJQEW5YE"]

      [DOCUMENTATION]
      ORG_NAME="Gold Eagle"
      ORG_DBA="Gold Eagle"
      ORG_URL="https://cassatorcorp.github.io"
      ORG_LOGO="https://cassatorcorp.github.io/photo1_2025.png"
      ORG_TWITTER="@_s_l_a_t_e_"
      ORG_DESCRIPTION="Issue your own tokens and trade on the SDEX decentralized exchange in real time with no fees.Gold Eagle is the perfect way to decentralize, store, manage, invest, trade, pay and move crypto assets."
      ORG_TWITTER="https://x.com/_s_l_a_t_e_"
      ORG_GITHUB="https://cassatorcorp.github.io"
      
      
      [[CURRENCIES]]
      name="Gold Eagle"
      code="Eagle"
      status="live"
      issuer="GBG35LS6GFWPZRC2T7O2FGXO2KQRQYLF5237YDWXXRFZRQHDKRP6EM3J"
      image="https://cassatorcorp.github.io/photo1_2025.png"
      display_decimals=7
      fixed_number=100000000000000000
