# CORRECTED stellar.toml
NETWORK_PASSPHRASE = "Public Global Stellar Network ; September 2015"

ACCOUNTS=[
"GBG35LS6GFWPZRC2T7O2FGXO2KQRQYLF5237YDWXXRFZRQHDKRP6EM3J",
"GBOYFPATHXCTWMDPC2U2KLGMUCJPCWTOYTLJN5U4B76XO7OWKJQEW5YE"]

[DOCUMENTATION]
ORG_NAME="Gold Eagle"
ORG_URL="https://cassatorcorp.github.io"
ORG_LOGO="https://cassatorcorp.github.io/photo1_2025.png"
ORG_DESCRIPTION="Gold Eagle Token: Digital representation of physical gold-backed assets"
ORG_TWITTER="https://x.com/_s_l_a_t_e_"


[[CURRENCIES]]
code="GOLDEAGLE"
name="Gold Eagle"
issuer="GBOYFPATHXCTWMDPC2U2KLGMUCJPCWTOYTLJN5U4B76XO7OWKJQEW5YE"
desc = "Gold Eagle Token: Digital representation of physical gold-backed assets"
redemption_instructions = "Redeem via Cassator Corp partners"
image="https://cassatorcorp.github.io/photo1_2025.png"
status="live"
display_decimals=7
fixed_number=10000000000000000000000
